config/routes.rb
Rails.application.routes.draw do
  resources :distances
  resources :posts
  resources :races
  resources :users

  # Go straight to home index page
  root 'home#index'

  # If adding friend
  get 'friendship' => 'users#add_friend', as: :friendship

  # If adding friend
  post 'friendship' => 'users#add_friend'

  # If login form is filled, handle login
  post 'login' => "home#handle_login", as: :login

  # If new user, lead to signup form
  get 'signup' => "home#signup", as: :signup

  # If signup form is filled, handle signup
  post 'signup' => "home#handle_signup"

  # Logout user
  get 'logout' => "home#handle_logout", as: :logout

  # Search for friends
  get 'search' => "users#search", as: :search

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
	has_many :user_races
	has_many :users, through: :user_races

	def self.search(search)
		where("name LIKE ? OR address LIKE ? OR city LIKE ? OR distance LIKE ? ", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
	end

    def to_json
        "{'id': #{id}, 'longitude': #{longitude}, 'latitude': #{latitude}, 'name': #{name}, 'address' : #{address}, 'city' : #{city}, 'state' : #{state}, 'date' : #{date}, 'distance' : #{distance}, 'details' : #{details}"
    end
    def to_h
        {
            id: id,
			name: name,
			date: date, 
			details: details,
			address: address,
			city: city,
			state: state,
            longitude: longitude.to_f,
            latitude: latitude.to_f,
			distance: distance
        }
	end
	
	geocoded_by :address       # can also be an IP address
	after_validation :geocode  # auto-fetch coordinates
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]


  # GET /races/1
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  def create
    @race = Race.new(race_params)
    Race.transaction do 
      @race.save
      UserRace.create( race_id: @race.id, user_id: @current_user.id)
    end
        respond_to do |format|
      if @race.id
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
  end
end

  # PATCH/PUT /races/1
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  def destroy
    Race.transaction do
      @race.user_races.destroy_all
      @race.destroy
    end
    respond_to do |format|
      format.html { redirect_back fallback_location: :root, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:name, :details, :date, :address, :city, :state, :distance, :latitude, :longitude)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<div class="form">
  <div class="form-table">
  <%= form_with(model: race, local: true) do |form| %>
    <% if race.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

        <ul>
        <% race.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <br><br>

    <h1>Submit a new race</h1>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :race_name %>
    </div>

    <div class="field">
      <%= form.label :details %>
      <%= form.text_area :details, id: :race_details %>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.datetime_select :date, id: :race_date %>
    </div>

    <div class="field">
      <%= form.label :address %>
      <%= form.text_field :address, id: :race_address %>
    </div>

    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city, id: :race_city %>
    </div>

    <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, :maxlength => 2, id: :race_state %>
  </div>

    <div class="field">
      <%= form.label :distance %>
      <%= form.select :distance, ['5K', '10K', 'Half-Marathon','Marathon'] %>
    </div>

    <div class="field">
      <%= form.hidden_field :latitude%>
      <%= form.hidden_field :latitude, id: :race_latitude %>
    </div>

    <div class="field">
      <%= form.hidden_field :longitude %>
      <%= form.hidden_field :longitude, id: :race_longitude %>
    </div>

    <script>
    document.addEventListener("DOMContentLoaded", function(){
      geocoder = new google.maps.Geocoder();
      address = document.getElementById("location")
      function getPlace (address){
          geocoder.geocode({'address': address}, function (results, status){
          coords = results[0].geometry.location;
          var temp1 = results[0].geometry.location.lat();
          var temp2 = results[0].geometry.location.lng();
          document.getElementById("latitude").value = temp1;
          document.getElementById("longitude").value = temp2;
      })
      
      }
    </script>

    <div class="actions">
      <%= form.submit %>
    </div>

  <% end %>

  </div>
</div>

app/views/races/edit.html.erb
<%= render 'home/navbar' %>

<div class="edit-race" class="page">

	<%= render 'form', race: @race %>

</div>

app/views/races/new.html.erb
<%= render 'home/navbar' %>

<div class="new-race" class="page">

	<%= render 'form', race: @race %>

	

</div>

app/views/races/show.html.erb
<%= render 'home/navbar' %>

<div class="race-page" class="page">

  <div class="race">

    <h2 style="display: inline-block;"><%= @race.name %></h2> | <%= link_to 'Edit', edit_race_path(@race) %> 

    <p>
      <strong>Date:</strong>
      <%= @race.date %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @race.address %>
    </p>

    <p>
      <strong>Details:</strong>
      <%= @race.details %>
    </p>

    <p>
      <strong>Distance:</strong>
      <%= @race.distance %>
    </p>

  </div>
</div>