config/routes.rb
Rails.application.routes.draw do
  resources :distances
  resources :posts
  resources :races
  resources :users

  # Go straight to home index page
  root 'home#index'

  # If adding friend
  get 'friendship' => 'users#add_friend', as: :friendship

  # If adding friend
  post 'friendship' => 'users#add_friend'

  # If login form is filled, handle login
  post 'login' => "home#handle_login", as: :login

  # If new user, lead to signup form
  get 'signup' => "home#signup", as: :signup

  # If signup form is filled, handle signup
  post 'signup' => "home#handle_signup"

  # Logout user
  get 'logout' => "home#handle_logout", as: :logout

  # Search for friends
  get 'search' => "users#search", as: :search

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_one :distance 
	has_many :user_races
	has_many :races, through: :user_races
	has_many :posts
	has_many :friendships
	has_many :friends, through: :friendships

	#This is the written logic to make sure we capture the friends posts.
	def friends_posts
		Post.where(user_id: [Friendship.where(user_id: id).map{|f| f.friend_id}])
	end

	def friends_races
		UserRace.where(user_id: [Friendship.where(user_id: id).map{|f| f.friend_id}])
	end

	def full_name
		first_name + ' ' + last_name
	end

  	# Search bar
	def self.search(search)
	  if search
	    User.where('first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%") 
	  else
	    User.find(:all)
	  end
	end

	# if friend
	def is_friend? (friend)
		friend_ids.include? friend.id
	end

	# change "style" for windows, "styles" for mac
	has_attached_file :photo, styles: { medium: "200x200>", thumb: "50x50>" }, default_url: "/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # Show all users in distance social group
  def index
    @distance = Distance.find_by(id: User.distance_id)
  end

  # GET /users/1
  # Show all of users posts
  def show
    @races = @current_user ? @current_user.races : []
    @distance = Distance.find_by(id: @current_user.distance_id)

  end

  def search
    @results = User.search(params[:search])
  end

  def add_friend
    @friend = Friendship.new(friendship_params)
    @friend.user_id = @current_user.id
    respond_to do |format|
      if @friend.save
      format.html { redirect_to :root, notice: 'Friend was successfully added.' }
      format.json { head :no_content }
      else
        format.html { render :root }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # Login form
  def login
    @user = User.find_by(email: params[:email])
    if user && user.password == params[:password]
      session[:user_id] = @user.id
      redirect_to :root
    else
      redirect_to back
    end
  end

  # POST /users
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to :root, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password, :photo, :distance_id)
    end

    def friendship_params
      params.permit(:friend_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form">
  <div class="form-table">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <h1>Sign Up</h1>

    <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo, id: :user_photo %>
    </div>

    <div class="field">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, id: :user_first_name %>
    </div>

    <div class="field">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, id: :user_last_name %>
    </div>

    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username, id: :user_username %>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password, id: :user_password %>
    </div>

<!--This is the group drop down selection  -->
    <div class="field">
      <%= form.label :distance_id %>
      <%= form.select :distance_id, [['5K', 1], ['10K', 2], ['Half-Marathon', 3], ['Marathon', 4]] %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<%= render 'home/navbar' %>

<div class="user-edit" class="page">

	<%= render 'form', user: @user %>

</div>

app/views/users/new.html.erb
<%= render 'home/navbar' %>

<div class="user-signup" class="page">

	<div class="signup-form">

	<%= render 'form', user: @user %>
	</div>

</div>

app/views/users/search.html.erb
<%= render 'home/navbar' %>

<div class="search-page">

	<div class="search-results">

		<h1>People</h1>

<% @results.each do |user| %>
	  <div>
	    <table>
	        <tr class="search-results__person">
	          <td><%= image_tag user.photo.url(:thumb) %></td>
	          <td>
	          <a style="font-size: 1.05em;" href="/users/<%= user.id %>">
	            <%= user.full_name %><br>

				  <%= link_to( "Add friend", friendship_path(friend_id: user.id)) unless @current_user.is_friend?(user) %>

	          </a>
	          </td>
	        </tr>
	    </table>
	  </div>
	  <br>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<%= render 'home/navbar' %>

<div class="container">
	<div class="profile">
			<div class="profile__info">
					<figure class="profile__shape"><%= image_tag @user.photo.url(:medium), class: "profile__photo--self" %></figure>				
					<div class="profile__description--self">
							<span class="profile__name">
								<%= @user.first_name %> <%= @user.last_name %>
								<% if params[:id] == @current_user.id.to_s %>
									<%= link_to 'EDIT', edit_user_path(@user), class: "profile__edit-user" %>
							 	<% end %>
							</span><br>
							<%= @distance.description %> Runner<br>
							<%= @user.city %>
					</div>
					<div class="profile__description--record">
									<span class="profile__name">Personal Record</span><br>
									Best Time: 02:00:00<br>
									Tally Count: 10                      
					</div>
			</div>
			<div class="container--races">
					<table class="profile__races">
							<th colspan="3" class="profile__title--races">
									Your Upcoming Races 
						
									<% if params[:id] == @current_user.id.to_s %>
										<%= link_to '<i class="fa fa-plus-circle profile__add-race" aria-hidden="true"></i>'.html_safe, new_race_path %>
									<% end %>
							</th>

							<% if @user.races.length > 0 %>
								<% @user.races.each do |race| %>

							<tr class="profile__race-item">
									<td class="profile__race-info">
											<span class="date"><%= race.date.strftime("%B %d, %Y") %></span> 
											<span class="date"><%= race.date.strftime("%I:%M%p") %></span>
											<%= link_to race.name, race %>
									</td>
									<td class="profile__race-info">
										<%= race.address %>
									</td>
							</tr>
								<% end %>
							<% else %>
							<p>You have no upcoming races.</p>
							<% end %>
					</table>
					<div class="profile__right-col">
							<table class="records__weather">
									<th class="profile__title--records" colspan="2">Weather</th>
									<tr class="profile__title--records" colspan="2">
											<td colspan="2">
													<input class="records__search--input" type="text" placeholder="Search..">
													<a href="#"><i class="fa fa-search records__search--icon" aria-hidden="true"></i></a>
											</td>

									</tr>

									<tr class="records__weather-info">
											<td class="records__weather-info--date" colspan="2">
													Friday, December 15, 2017
											</td>
									</tr>

									<tr class="records__weather-info">
											<td class="records__weather-info--forecast" colspan="2">
													<span class="date">08:00AM</span> Clear sky | -4°C degrees
											</td>
									</tr>
							</table>

							<table class="profile__records">
									<th class="profile__title--records profile__friends" colspan="2">Friends List</th>
									<tr class="profile__record">
											<td class="profile__record-item" colspan="2">
													Jane Doe
											</td>
									</tr>
									<tr class="profile__record">
											<td class="profile__record-item" colspan="2">
													View All
											</td>
									</tr>
							</table>
					</div>
			</div>
			<div class="profile__posts">
							<h3 class="profile__title--posts">
									Your Posts
									<% if params[:id] == @current_user.id.to_s %>
										<%= link_to '<i class="fa fa-plus-circle profile__add-post" aria-hidden="true"></i>'.html_safe, new_post_path %>
									<% end %>
							</h3>
							<% if @user.posts.length > 0 %>
								<% @user.posts.each do |post| %>
								<%= link_to post do %>
								<div class="profile__post-item">
										<%= image_tag post.photo.url(:medium), class: "profile__post-photo" %>
										<span class="profile__post-description">
												<span class="profile__post-description--title">
													<%= post.title %>
												</span>
												<span class="profile__post-description--date">
													<%=post.created_at.strftime("%A, %b %e, %Y") %> | <%=post.created_at.in_time_zone(-4).strftime("%I:%M %p") %>
												</span>
												<span class="profile__post-description--details">
														Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ac nisi quis dolor luctus tristique. Nunc non pulvinar est. Suspendisse lacinia, urna eget ornare accumsan, dolor eros sodales diam, ut consectetur lacus augue nec quam. Fusce consequat a ante eu tempus. Integer vehicula purus ac mauris suscipit elementum. Cras rutrum convallis turpis vel malesuada. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce in urna id nisl posuere ullamcorper. Aenean eget lacus ante. Cras in fringilla sem. In sit amet rhoncus quam, ut posuere dolor. Fusce nec mi nunc.
												</span>
										</span>
								</div>
								<% end %>

									<% end %>
							<% else %>
								<p>You have no posts.</p>
							<% end %>

				</div>
	</div>
</div>