config/routes.rb
Rails.application.routes.draw do
  resources :distances
  resources :posts
  resources :races
  resources :users

  # Go straight to home index page
  root 'home#index'

  # If adding friend
  get 'friendship' => 'users#add_friend', as: :friendship

  # If adding friend
  post 'friendship' => 'users#add_friend'

  # If login form is filled, handle login
  post 'login' => "home#handle_login", as: :login

  # If new user, lead to signup form
  get 'signup' => "home#signup", as: :signup

  # If signup form is filled, handle signup
  post 'signup' => "home#handle_signup"

  # Logout user
  get 'logout' => "home#handle_logout", as: :logout

  # Search for friends
  get 'search' => "users#search", as: :search

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	# Newsfeed of posts from friends
	def index
		redirect_to posts_path
	end

	def handle_search
		@projects = Project.search(params[:search])
	end

	# Post method to handle login, go to posts#index
	def handle_login
		user = User.find_by(username: params[:user][:username])
		if user && user.password == params[:user][:password]
		  session[:user_id]= user.id
		  redirect_to posts_path
		else
		  redirect_to :root
		end
	end

	# Handle logout, go to login page
	def handle_logout
		session[:user_id] = nil
		redirect_to :root
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<div class="header">
	
</div>

app/views/home/_login.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
<nav class="landing-navigation">
	<div class="landing-navigation__logo">LD<span style="color: white;">RUNNER</span></div>
	<ul class="landing-navigation__list-items">
		<li class="landing-navigation__login">
			<%= form_for User.new, url: login_path, action: :post do |f| %>
				<%= f.label :username %>
				<%= f.text_field :username%> &nbsp;
				<%= f.label :password %>
				<%= f.password_field :password %>
				<%= f.submit "Sign in" %>
			<% end %>		
		</li>
	</ul>
</nav>

<div class="landing">
	<img class="landing-photo" src="landing.jpg"/>
	<div class="landing-top">

	<%= link_to 'New User', new_user_path %>

	<div class="examples">
		Examples:<br>
		Username = ckusuma, Password = 1<br>
		Username = kgallagher, Password = 2
	</div>

</div>

app/views/home/_navbar.html.erb
<% if @current_user %>
<script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
	<nav class="navigation">
		<div class="navigation__logo">LD<span style="color: white;">RUNNER</span></div>
		<%= render 'home/searchbar' %>
		<ul class="navigation__list-items">
			<li class="navigation__list-item--1"><%= link_to 'Home', posts_path %></li> | 
			<li class="navigation__list-item--2"><%= link_to 'Profile', user_path(@current_user) %></li> |
			<li class="navigation__list-item--3"><%= link_to 'Races', distance_path(@current_user) %></li> |
			<li class="navigation__list-item--4"><%= link_to 'Logout', :logout %></li>
		</ul>
	</nav>
<% end %>

app/views/home/_searchbar.html.erb
<div class="navigation__search-bar">

	<%= form_tag search_path, :method => 'get' do %>
		<%= text_field_tag :search, params[:search], :class => 'navigation__search-bar--input', placeholder: "Search friends..." %>
		<%= button_tag(type: "submit", class: 'navigation__search-bar--button') do %>
			<i class="fa fa-search" aria-hidden="true"></i>
		<% end %>
	<% end %> 

</div>